[tools]
air = "1.63.0"
bun = "1.3.2"
go = "1.25.4"
"go:github.com/cweill/gotests/gotests" = "1.9.0"
"go:github.com/gzuidhof/tygo" = "0.2.19"
"go:github.com/spf13/cobra-cli" = "latest"
golangci-lint = "2.6.1"
task = "3.45.5"
